### ISSUE TITLE
Java: replace java-devel with java-openjdk-devel

### ISSUE THREAD

**Issue by jackorp** [developer-portal/content#435]
This is a reminder issue for a future update to replace `sudo dnf install java-devel` with `sudo dnf install java-openjdk-devel` when it will become possible.

Java devel virtual package should be installable through `sudo dnf install java-openjdk-devel`, but that is not currently possible, so `java-devel` package is used instead.

Filed in Fedora as https://bugzilla.redhat.com/show_bug.cgi?id=2084332 by @mizdebsk .

Initial PR: https://github.com/developer-portal/content/pull/434

**Comment by zad999** [comment]
i get this error when i run my code :
Exception in thread "main" java.lang.IllegalArgumentException: Illegal base64 character 2e
	at java.base/java.util.Base64$Decoder.decode0(Base64.java:847)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:566)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:589)
	at kerberos.cryptotechniques.EncryptorDecryptor.decrypt(EncryptorDecryptor.java:112)
	at kerberos.client.Client.parseResponseFromAuthenticationServer(Client.java:186)
	at kerberos.client.Client.main(Client.java:82)
C:\Users\elathir\AppData\Local\NetBeans\Cache\13\executor-snippets\run.xml:111: The following error occurred while executing this line:
C:\Users\elathir\AppData\Local\NetBeans\Cache\13\executor-snippets\run.xml:68: Java returned: 1

**Comment by Melophip** [comment]
Can I be assigned this issue?

**Comment by jackorp** [comment]
The upstream bug does not seem to even have gotten a response other than auto-close.

Let's assume that the current approach is "correct".
